import {
  activateDeepAnalysisWorkflowDraft,
  addProjectMembership,
  applyProjectLearningProposal,
  approveAdminMcpRevision,
  archiveProject,
  batchTagKnowledgeDocuments,
  bindMcpSecret,
  cancelDeepAnalysisMission,
  checkoutSkillDraft,
  compareSkillVersions,
  createAdminAnnouncement,
  createAdminMcpDefinition,
  createAdminMcpRevision,
  createAdminUser,
  createDeepAnalysisMission,
  createDeepAnalysisMissionExport,
  createDeepAnalysisPattern,
  createDeepAnalysisPatternVersion,
  createDeepAnalysisWorkflowDraft,
  createHelpItem,
  createKnowledgeSpace,
  createKnowledgeTag,
  createProjectFolder,
  createProjectLearningProposal,
  createScheduledTask,
  createSkill,
  deleteAdminAnnouncement,
  deleteDeepAnalysisMission,
  deleteDeepAnalysisPattern,
  deleteExtension,
  deleteHelpItem,
  deleteKnowledgeDocument,
  deleteMemory,
  deleteProjectFile,
  deleteProjectFolder,
  removeProjectMembership,
  deleteScheduledTask,
  downloadProjectFile,
  emergencyStopAllAdminRuns,
  exportAdminConversations,
  getAdminAuditTraffic,
  getAdminConversation,
  getAdminRunSafetySettings,
  getAdminUsageStatistics,
  getDeepAnalysisClaims,
  getDeepAnalysisEvidence,
  getDeepAnalysisMission,
  getDeepAnalysisMissionCosts,
  getDeepAnalysisMissionProjection,
  getDeepAnalysisOpenIssues,
  getDeepAnalysisRefreshPreview,
  getDeepAnalysisResearchInspector,
  getRepositoryExtensionState,
  getExtensionVersion,
  listHelpItems,
  getKnowledgeDocument,
  getKnowledgeGraph,
  listMcpInstallations,
  getMemorySettings,
  getProjectFile,
  getProjectMemoryHistory,
  getSkillDraft,
  installExtensionVersion,
  installMcp,
  listAdminAnnouncements,
  listAdminAuditEvents,
  listAdminConversations,
  listAdminMcpDefinitions,
  listAdminUsers,
  listDeepAnalysisMissionEvents,
  listDeepAnalysisMissions,
  listDeepAnalysisPatterns,
  listExtensionInstallations,
  listExtensions,
  listKnowledgeDocuments,
  listKnowledgeSpaces,
  listKnowledgeTags,
  listKnowledgeTagProposals,
  listMcpCatalog,
  listMemories,
  listProjectFiles,
  listProjectFolders,
  listProjectLearningProposals,
  listProjectMemories,
  listProjectMemberships,
  listScheduledRuns,
  listScheduledTasks,
  listSkillCatalog,
  listTrashedExtensions,
  moveDeepAnalysisMission,
  moveProjectFile,
  moveProjectFolder,
  openDeepAnalysisMissionEventStream,
  optimizeMemories,
  pauseDeepAnalysisMission,
  publishDeepAnalysisPatternVersion,
  regenerateDeepAnalysisWorkflow,
  removeSkillOwnership,
  resetAdminUserPassword,
  restartDeepAnalysisMission,
  restoreExtension,
  resumeDeepAnalysisMission,
  retryDeepAnalysisMission,
  reviewProjectLearningProposal,
  rollbackSkillVersion,
  rollbackProjectLearningProposal,
  runDeepAnalysisQualityGate,
  runScheduledTaskNow,
  saveKnowledgeDocumentFromMessage,
  resolveKnowledgeTagProposal,
  resolveKnowledgeTagProposals,
  saveSkillVersion,
  setAdminMcpDefinitionStatus,
  setExtensionInstallationEnabled,
  setMcpInstallationEnabled,
  setScheduledTaskEnabled,
  setSkillCatalogLike,
  startDeepAnalysisMission,
  steerDeepAnalysisMission,
  syncRepositoryExtensions,
  testMcpInstallationAnswer,
  unbindMcpSecret,
  uninstallExtension,
  uninstallMcp,
  updateAdminAnnouncement,
  updateAdminRunSafetySettings,
  updateAdminUser,
  updateDeepAnalysisMission,
  updateDeepAnalysisWorkflowDraft,
  updateExtensionInstallationProjects,
  updateExtensionMetadata,
  updateHelpItem,
  updateKnowledgeSpace,
  updateKnowledgeDocumentTags,
  updateKnowledgeTag,
  updateMcpInstallationProjects,
  updateMemory,
  updateMemorySettings,
  updateProjectMembership,
  updateScheduledTask,
  updateSkillDraft,
  uploadProjectFile,
  uploadProjectFileVersion,
  verifyMcpInstallation,
  answerDeepAnalysisDecision,
  refreshDeepAnalysisMission,
  addSkillOwnership,
} from "./api";

export const deepAnalysisSidebarApi = {
  updateMission: updateDeepAnalysisMission,
  moveMission: moveDeepAnalysisMission,
  deleteMission: deleteDeepAnalysisMission,
};

export const deepAnalysisApi = {
  listMissions: listDeepAnalysisMissions,
  createMission: createDeepAnalysisMission,
  listPatterns: listDeepAnalysisPatterns,
  createPattern: createDeepAnalysisPattern,
  createPatternVersion: createDeepAnalysisPatternVersion,
  publishPatternVersion: publishDeepAnalysisPatternVersion,
  deletePattern: deleteDeepAnalysisPattern,
  getMission: getDeepAnalysisMission,
  listEvents: listDeepAnalysisMissionEvents,
  getProjection: getDeepAnalysisMissionProjection,
  openEventStream: openDeepAnalysisMissionEventStream,
  getCosts: getDeepAnalysisMissionCosts,
  getClaims: getDeepAnalysisClaims,
  getEvidence: getDeepAnalysisEvidence,
  getOpenIssues: getDeepAnalysisOpenIssues,
  createExport: createDeepAnalysisMissionExport,
  createDraft: createDeepAnalysisWorkflowDraft,
  updateDraft: updateDeepAnalysisWorkflowDraft,
  activateDraft: activateDeepAnalysisWorkflowDraft,
  regenerateWorkflow: regenerateDeepAnalysisWorkflow,
  startMission: startDeepAnalysisMission,
  cancelMission: cancelDeepAnalysisMission,
  pauseMission: pauseDeepAnalysisMission,
  resumeMission: resumeDeepAnalysisMission,
  retryMission: retryDeepAnalysisMission,
  restartMission: restartDeepAnalysisMission,
  getResearchInspector: getDeepAnalysisResearchInspector,
  getRefreshPreview: getDeepAnalysisRefreshPreview,
  steerMission: steerDeepAnalysisMission,
  refreshMission: refreshDeepAnalysisMission,
  deleteMission: deleteDeepAnalysisMission,
  updateMission: updateDeepAnalysisMission,
  moveMission: moveDeepAnalysisMission,
  answerDecision: answerDeepAnalysisDecision,
  runQualityGate: runDeepAnalysisQualityGate,
};

export const knowledgeApi = {
  listSpaces: listKnowledgeSpaces,
  createSpace: createKnowledgeSpace,
  updateSpace: updateKnowledgeSpace,
  listTags: listKnowledgeTags,
  listTagProposals: listKnowledgeTagProposals,
  createTag: createKnowledgeTag,
  updateTag: updateKnowledgeTag,
  listDocuments: listKnowledgeDocuments,
  getDocument: getKnowledgeDocument,
  updateDocumentTags: updateKnowledgeDocumentTags,
  deleteDocument: deleteKnowledgeDocument,
  saveMessage: saveKnowledgeDocumentFromMessage,
  batchTagDocuments: batchTagKnowledgeDocuments,
  resolveTagProposal: resolveKnowledgeTagProposal,
  resolveTagProposals: resolveKnowledgeTagProposals,
  getGraph: getKnowledgeGraph,
};

export const projectFilesApi = {
  list: listProjectFiles,
  get: getProjectFile,
  upload: uploadProjectFile,
  uploadVersion: uploadProjectFileVersion,
  move: moveProjectFile,
  download: downloadProjectFile,
  delete: deleteProjectFile,
  listFolders: listProjectFolders,
  createFolder: createProjectFolder,
  moveFolder: moveProjectFolder,
  deleteFolder: deleteProjectFolder,
};

export const extensionsApi = {
  list: listExtensions,
  listCatalog: listSkillCatalog,
  setLike: setSkillCatalogLike,
  syncRepository: syncRepositoryExtensions,
  getRepositoryState: getRepositoryExtensionState,
  listTrash: listTrashedExtensions,
  getVersion: getExtensionVersion,
  compareVersions: compareSkillVersions,
  rollbackVersion: rollbackSkillVersion,
  getDraft: getSkillDraft,
  checkoutDraft: checkoutSkillDraft,
  updateMetadata: updateExtensionMetadata,
  delete: deleteExtension,
  restore: restoreExtension,
  createSkill,
  updateDraft: updateSkillDraft,
  saveVersion: saveSkillVersion,
  addOwnership: addSkillOwnership,
  removeOwnership: removeSkillOwnership,
  listInstallations: listExtensionInstallations,
  install: installExtensionVersion,
  setEnabled: setExtensionInstallationEnabled,
  updateProjects: updateExtensionInstallationProjects,
  uninstall: uninstallExtension,
};

export const mcpApi = {
  listCatalog: listMcpCatalog,
  listInstallations: listMcpInstallations,
  install: installMcp,
  setEnabled: setMcpInstallationEnabled,
  updateProjects: updateMcpInstallationProjects,
  verify: verifyMcpInstallation,
  testAnswer: testMcpInstallationAnswer,
  uninstall: uninstallMcp,
  bindSecret: bindMcpSecret,
  unbindSecret: unbindMcpSecret,
};

export const schedulesApi = {
  list: listScheduledTasks,
  create: createScheduledTask,
  update: updateScheduledTask,
  setEnabled: setScheduledTaskEnabled,
  delete: deleteScheduledTask,
  runNow: runScheduledTaskNow,
  listRuns: listScheduledRuns,
};

export const memoriesApi = {
  list: listMemories,
  update: updateMemory,
  delete: deleteMemory,
  getSettings: getMemorySettings,
  updateSettings: updateMemorySettings,
  optimize: optimizeMemories,
};

export const projectMemoriesApi = {
  list: listProjectMemories,
  getHistory: getProjectMemoryHistory,
  listProposals: listProjectLearningProposals,
  createProposal: createProjectLearningProposal,
  reviewProposal: reviewProjectLearningProposal,
  applyProposal: applyProjectLearningProposal,
  rollbackProposal: rollbackProjectLearningProposal,
};

export const adminApi = {
  listAnnouncements: listAdminAnnouncements,
  createAnnouncement: createAdminAnnouncement,
  updateAnnouncement: updateAdminAnnouncement,
  deleteAnnouncement: deleteAdminAnnouncement,
  getUsageStatistics: getAdminUsageStatistics,
  getRunSafetySettings: getAdminRunSafetySettings,
  updateRunSafetySettings: updateAdminRunSafetySettings,
  emergencyStopAllRuns: emergencyStopAllAdminRuns,
  listUsers: listAdminUsers,
  createUser: createAdminUser,
  updateUser: updateAdminUser,
  resetPassword: resetAdminUserPassword,
  listConversations: listAdminConversations,
  getConversation: getAdminConversation,
  exportConversations: exportAdminConversations,
  listAuditEvents: listAdminAuditEvents,
  getAuditTraffic: getAdminAuditTraffic,
  listMcpDefinitions: listAdminMcpDefinitions,
  createMcpDefinition: createAdminMcpDefinition,
  createMcpRevision: createAdminMcpRevision,
  approveMcpRevision: approveAdminMcpRevision,
  setMcpStatus: setAdminMcpDefinitionStatus,
};

export const projectMembershipsApi = {
  list: listProjectMemberships,
  add: addProjectMembership,
  update: updateProjectMembership,
  remove: removeProjectMembership,
};

export const helpApi = {
  list: listHelpItems,
  create: createHelpItem,
  update: updateHelpItem,
  delete: deleteHelpItem,
};
