"""extensions and scheduled tasks

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-11 18:45:01.317131
"""

from typing import Sequence, Union

from alembic import op
import lumina.models
import sqlalchemy as sa


revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_folders",
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("parent_folder_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("normalized_name", sa.String(length=160), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "archived_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_skill_folders_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_folder_id"],
            ["skill_folders.id"],
            name=op.f("fk_skill_folders_parent_folder_id_skill_folders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_folders")),
        sa.UniqueConstraint(
            "scope_type",
            "scope_id",
            "parent_folder_id",
            "normalized_name",
            name=op.f("uq_skill_folders_scope_type"),
        ),
    )
    op.create_index(
        op.f("ix_skill_folders_parent_folder_id"),
        "skill_folders",
        ["parent_folder_id"],
        unique=False,
    )
    op.create_index(
        "ix_skill_folders_tree",
        "skill_folders",
        ["scope_type", "scope_id", "parent_folder_id"],
        unique=False,
    )
    op.create_table(
        "extensions",
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("publisher_user_id", sa.String(length=36), nullable=True),
        sa.Column("latest_published_version_id", sa.String(length=36), nullable=True),
        sa.Column("forked_from_extension_id", sa.String(length=36), nullable=True),
        sa.Column("forked_from_version_id", sa.String(length=36), nullable=True),
        sa.Column(
            "archived_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["forked_from_extension_id"],
            ["extensions.id"],
            name=op.f("fk_extensions_forked_from_extension_id_extensions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_extensions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_extensions_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extensions_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["publisher_user_id"],
            ["users.id"],
            name=op.f("fk_extensions_publisher_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extensions")),
        sa.UniqueConstraint(
            "owner_user_id", "slug", name=op.f("uq_extensions_owner_user_id")
        ),
    )
    op.create_index(
        "ix_extensions_catalog",
        "extensions",
        ["organization_id", "kind", "visibility"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extensions_organization_id"),
        "extensions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extensions_owner_user_id"),
        "extensions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extensions_project_id"), "extensions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_extensions_visibility"), "extensions", ["visibility"], unique=False
    )
    op.create_table(
        "extension_versions",
        sa.Column("extension_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.String(length=36), nullable=True),
        sa.Column("package_json", sa.JSON(), nullable=False),
        sa.Column("package_digest", sa.String(length=64), nullable=False),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "published_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "revoked_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_extension_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["extension_id"],
            ["extensions.id"],
            name=op.f("fk_extension_versions_extension_id_extensions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["extension_versions.id"],
            name=op.f("fk_extension_versions_parent_version_id_extension_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_versions")),
        sa.UniqueConstraint(
            "extension_id",
            "version_number",
            name=op.f("uq_extension_versions_extension_id"),
        ),
    )
    op.create_index(
        op.f("ix_extension_versions_extension_id"),
        "extension_versions",
        ["extension_id"],
        unique=False,
    )
    op.create_index(
        "ix_extension_versions_status",
        "extension_versions",
        ["extension_id", "status"],
        unique=False,
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("schedule_kind", sa.String(length=24), nullable=False),
        sa.Column("schedule_config_json", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("context_mode", sa.String(length=32), nullable=False),
        sa.Column("source_conversation_id", sa.String(length=36), nullable=True),
        sa.Column("provider_id", sa.String(length=80), nullable=False),
        sa.Column("model_key", sa.String(length=160), nullable=False),
        sa.Column("effort", sa.String(length=32), nullable=True),
        sa.Column("extension_policy_json", sa.JSON(), nullable=False),
        sa.Column("delivery_policy_json", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "next_run_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "last_run_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "archived_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_scheduled_tasks_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_scheduled_tasks_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_scheduled_tasks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
            name=op.f("fk_scheduled_tasks_source_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
    )
    op.create_index(
        "ix_scheduled_tasks_due",
        "scheduled_tasks",
        ["enabled", "next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_next_run_at"),
        "scheduled_tasks",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_organization_id"),
        "scheduled_tasks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_owner_user_id"),
        "scheduled_tasks",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_tasks_project",
        "scheduled_tasks",
        ["project_id", "archived_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_project_id"),
        "scheduled_tasks",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "skill_folder_placements",
        sa.Column("folder_id", sa.String(length=36), nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("moved_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("moved_at", lumina.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["skill_folders.id"],
            name=op.f("fk_skill_folder_placements_folder_id_skill_folders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["moved_by_user_id"],
            ["users.id"],
            name=op.f("fk_skill_folder_placements_moved_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["extensions.id"],
            name=op.f("fk_skill_folder_placements_skill_id_extensions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_folder_placements")),
        sa.UniqueConstraint(
            "skill_id",
            "scope_type",
            "scope_id",
            name=op.f("uq_skill_folder_placements_skill_id"),
        ),
    )
    op.create_index(
        op.f("ix_skill_folder_placements_folder_id"),
        "skill_folder_placements",
        ["folder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_folder_placements_skill_id"),
        "skill_folder_placements",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "extension_drafts",
        sa.Column("extension_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("base_version_id", sa.String(length=36), nullable=True),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("current_digest", sa.String(length=64), nullable=False),
        sa.Column("package_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source_conversation_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_version_id"],
            ["extension_versions.id"],
            name=op.f("fk_extension_drafts_base_version_id_extension_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["extension_id"],
            ["extensions.id"],
            name=op.f("fk_extension_drafts_extension_id_extensions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_extension_drafts_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversations.id"],
            name=op.f("fk_extension_drafts_source_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_drafts")),
        sa.UniqueConstraint(
            "extension_id", name=op.f("uq_extension_drafts_extension_id")
        ),
    )
    op.create_index(
        op.f("ix_extension_drafts_base_version_id"),
        "extension_drafts",
        ["base_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_drafts_extension_id"),
        "extension_drafts",
        ["extension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_drafts_owner_user_id"),
        "extension_drafts",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_drafts_status"), "extension_drafts", ["status"], unique=False
    )
    op.create_table(
        "extension_installations",
        sa.Column("extension_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("installed_by_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "installed_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "removed_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["extension_id"],
            ["extensions.id"],
            name=op.f("fk_extension_installations_extension_id_extensions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_extension_installations_installed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["extension_versions.id"],
            name=op.f("fk_extension_installations_version_id_extension_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_installations")),
    )
    op.create_index(
        "ix_extension_installations_active",
        "extension_installations",
        ["scope_type", "scope_id", "enabled", "removed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_installations_extension_id"),
        "extension_installations",
        ["extension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_installations_version_id"),
        "extension_installations",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_runs",
        sa.Column("scheduled_task_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("trigger_type", sa.String(length=24), nullable=False),
        sa.Column(
            "scheduled_for", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("output_artifact_ids_json", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "started_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "finished_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_scheduled_runs_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_scheduled_runs_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_task_id"],
            ["scheduled_tasks.id"],
            name=op.f("fk_scheduled_runs_scheduled_task_id_scheduled_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_runs")),
        sa.UniqueConstraint(
            "scheduled_task_id",
            "idempotency_key",
            name="uq_scheduled_runs_task_idempotency",
        ),
        sa.UniqueConstraint(
            "scheduled_task_id",
            "scheduled_for",
            name="uq_scheduled_runs_task_scheduled_for",
        ),
    )
    op.create_index(
        "ix_scheduled_runs_history",
        "scheduled_runs",
        ["scheduled_task_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_runs_run_id"), "scheduled_runs", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_runs_scheduled_task_id"),
        "scheduled_runs",
        ["scheduled_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_runs_status"), "scheduled_runs", ["status"], unique=False
    )
    op.create_table(
        "extension_draft_bindings",
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("bound_at", lumina.models.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["extension_drafts.id"],
            name=op.f("fk_extension_draft_bindings_draft_id_extension_drafts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extension_draft_bindings_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_extension_draft_bindings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_draft_bindings")),
        sa.UniqueConstraint(
            "draft_id",
            "user_id",
            "project_id",
            name=op.f("uq_extension_draft_bindings_draft_id"),
        ),
    )
    op.create_index(
        op.f("ix_extension_draft_bindings_draft_id"),
        "extension_draft_bindings",
        ["draft_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_draft_bindings_project_id"),
        "extension_draft_bindings",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extension_draft_bindings_user_id"),
        "extension_draft_bindings",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "extension_draft_revisions",
        sa.Column("draft_id", sa.String(length=36), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("package_json", sa.JSON(), nullable=False),
        sa.Column("package_digest", sa.String(length=64), nullable=False),
        sa.Column("change_summary", sa.String(length=500), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_extension_draft_revisions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["extension_drafts.id"],
            name=op.f("fk_extension_draft_revisions_draft_id_extension_drafts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extension_draft_revisions")),
        sa.UniqueConstraint(
            "draft_id",
            "revision_number",
            name=op.f("uq_extension_draft_revisions_draft_id"),
        ),
    )
    op.create_index(
        op.f("ix_extension_draft_revisions_draft_id"),
        "extension_draft_revisions",
        ["draft_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_extension_draft_revisions_draft_id"),
        table_name="extension_draft_revisions",
    )
    op.drop_table("extension_draft_revisions")
    op.drop_index(
        op.f("ix_extension_draft_bindings_user_id"),
        table_name="extension_draft_bindings",
    )
    op.drop_index(
        op.f("ix_extension_draft_bindings_project_id"),
        table_name="extension_draft_bindings",
    )
    op.drop_index(
        op.f("ix_extension_draft_bindings_draft_id"),
        table_name="extension_draft_bindings",
    )
    op.drop_table("extension_draft_bindings")
    op.drop_index(op.f("ix_scheduled_runs_status"), table_name="scheduled_runs")
    op.drop_index(
        op.f("ix_scheduled_runs_scheduled_task_id"), table_name="scheduled_runs"
    )
    op.drop_index(op.f("ix_scheduled_runs_run_id"), table_name="scheduled_runs")
    op.drop_index("ix_scheduled_runs_history", table_name="scheduled_runs")
    op.drop_table("scheduled_runs")
    op.drop_index(
        op.f("ix_extension_installations_version_id"),
        table_name="extension_installations",
    )
    op.drop_index(
        op.f("ix_extension_installations_extension_id"),
        table_name="extension_installations",
    )
    op.drop_index(
        "ix_extension_installations_active", table_name="extension_installations"
    )
    op.drop_table("extension_installations")
    op.drop_index(op.f("ix_extension_drafts_status"), table_name="extension_drafts")
    op.drop_index(
        op.f("ix_extension_drafts_owner_user_id"), table_name="extension_drafts"
    )
    op.drop_index(
        op.f("ix_extension_drafts_extension_id"), table_name="extension_drafts"
    )
    op.drop_index(
        op.f("ix_extension_drafts_base_version_id"), table_name="extension_drafts"
    )
    op.drop_table("extension_drafts")
    op.drop_index(
        op.f("ix_skill_folder_placements_skill_id"),
        table_name="skill_folder_placements",
    )
    op.drop_index(
        op.f("ix_skill_folder_placements_folder_id"),
        table_name="skill_folder_placements",
    )
    op.drop_table("skill_folder_placements")
    op.drop_index(op.f("ix_scheduled_tasks_project_id"), table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_project", table_name="scheduled_tasks")
    op.drop_index(
        op.f("ix_scheduled_tasks_owner_user_id"), table_name="scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_scheduled_tasks_organization_id"), table_name="scheduled_tasks"
    )
    op.drop_index(op.f("ix_scheduled_tasks_next_run_at"), table_name="scheduled_tasks")
    op.drop_index("ix_scheduled_tasks_due", table_name="scheduled_tasks")
    op.drop_table("scheduled_tasks")
    op.drop_index("ix_extension_versions_status", table_name="extension_versions")
    op.drop_index(
        op.f("ix_extension_versions_extension_id"), table_name="extension_versions"
    )
    op.drop_table("extension_versions")
    op.drop_index(op.f("ix_extensions_visibility"), table_name="extensions")
    op.drop_index(op.f("ix_extensions_project_id"), table_name="extensions")
    op.drop_index(op.f("ix_extensions_owner_user_id"), table_name="extensions")
    op.drop_index(op.f("ix_extensions_organization_id"), table_name="extensions")
    op.drop_index("ix_extensions_catalog", table_name="extensions")
    op.drop_table("extensions")
    op.drop_index("ix_skill_folders_tree", table_name="skill_folders")
    op.drop_index(op.f("ix_skill_folders_parent_folder_id"), table_name="skill_folders")
    op.drop_table("skill_folders")
    # ### end Alembic commands ###
