"""message interactions and user memories

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-11 18:58:06.338486
"""

from typing import Sequence, Union

from alembic import op
import lumina.models
import sqlalchemy as sa


revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_memories",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("normalized_fact", sa.String(length=1000), nullable=False),
        sa.Column("display_text", sa.Text(), nullable=False),
        sa.Column("source_message_ids_json", sa.JSON(), nullable=False),
        sa.Column("source_run_ids_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("supersedes_memory_id", sa.String(length=36), nullable=True),
        sa.Column("extractor_version", sa.String(length=80), nullable=False),
        sa.Column(
            "first_learned_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "last_confirmed_at",
            lumina.models.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "deleted_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["supersedes_memory_id"],
            ["user_memories.id"],
            name=op.f("fk_user_memories_supersedes_memory_id_user_memories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_memories_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_memories")),
    )
    op.create_index(
        op.f("ix_user_memories_expires_at"),
        "user_memories",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_memories_fact",
        "user_memories",
        ["user_id", "normalized_fact"],
        unique=False,
    )
    op.create_index(
        "ix_user_memories_listing",
        "user_memories",
        ["user_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_memories_status"), "user_memories", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_memories_user_id"), "user_memories", ["user_id"], unique=False
    )
    op.create_table(
        "message_feedback",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("rating_value", sa.String(length=16), nullable=True),
        sa.Column("report_category", sa.String(length=64), nullable=True),
        sa.Column("report_description", sa.Text(), nullable=True),
        sa.Column("diagnostic_scope_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "deleted_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_feedback_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_feedback")),
    )
    op.create_index(
        op.f("ix_message_feedback_message_id"),
        "message_feedback",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_feedback_reports",
        "message_feedback",
        ["message_id", "kind", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_feedback_status"), "message_feedback", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_user_id"),
        "message_feedback",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_message_feedback_active_rating",
        "message_feedback",
        ["user_id", "message_id"],
        unique=True,
        sqlite_where=sa.text("kind = 'rating' AND deleted_at IS NULL"),
        postgresql_where=sa.text("kind = 'rating' AND deleted_at IS NULL"),
    )
    op.create_table(
        "message_references",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("reference_id", sa.String(length=36), nullable=False),
        sa.Column("version_or_digest", sa.String(length=160), nullable=True),
        sa.Column("token_start", sa.Integer(), nullable=False),
        sa.Column("token_end", sa.Integer(), nullable=True),
        sa.Column("display_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_references_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_references")),
        sa.UniqueConstraint(
            "message_id",
            "kind",
            "reference_id",
            "token_start",
            name=op.f("uq_message_references_message_id"),
        ),
    )
    op.create_index(
        op.f("ix_message_references_message_id"),
        "message_references",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        "ix_message_references_target",
        "message_references",
        ["kind", "reference_id"],
        unique=False,
    )
    op.create_table(
        "message_selection_comments",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("author_user_id", sa.String(length=36), nullable=False),
        sa.Column("source_message_hash", sa.String(length=64), nullable=False),
        sa.Column("block_id", sa.String(length=160), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("selected_text", sa.Text(), nullable=False),
        sa.Column("prefix_context", sa.String(length=500), nullable=False),
        sa.Column("suffix_context", sa.String(length=500), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("anchor_status", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", lumina.models.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "deleted_at", lumina.models.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_message_selection_comments_author_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_selection_comments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_selection_comments")),
    )
    op.create_index(
        "ix_message_comments_owner",
        "message_selection_comments",
        ["author_user_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_selection_comments_author_user_id"),
        "message_selection_comments",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_selection_comments_message_id"),
        "message_selection_comments",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_selection_comments_status"),
        "message_selection_comments",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_selection_comments_status"),
        table_name="message_selection_comments",
    )
    op.drop_index(
        op.f("ix_message_selection_comments_message_id"),
        table_name="message_selection_comments",
    )
    op.drop_index(
        op.f("ix_message_selection_comments_author_user_id"),
        table_name="message_selection_comments",
    )
    op.drop_index("ix_message_comments_owner", table_name="message_selection_comments")
    op.drop_table("message_selection_comments")
    op.drop_index("ix_message_references_target", table_name="message_references")
    op.drop_index(
        op.f("ix_message_references_message_id"), table_name="message_references"
    )
    op.drop_table("message_references")
    op.drop_index(
        "uq_message_feedback_active_rating",
        table_name="message_feedback",
        sqlite_where=sa.text("kind = 'rating' AND deleted_at IS NULL"),
        postgresql_where=sa.text("kind = 'rating' AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_message_feedback_user_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_status"), table_name="message_feedback")
    op.drop_index("ix_message_feedback_reports", table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_message_id"), table_name="message_feedback")
    op.drop_table("message_feedback")
    op.drop_index(op.f("ix_user_memories_user_id"), table_name="user_memories")
    op.drop_index(op.f("ix_user_memories_status"), table_name="user_memories")
    op.drop_index("ix_user_memories_listing", table_name="user_memories")
    op.drop_index("ix_user_memories_fact", table_name="user_memories")
    op.drop_index(op.f("ix_user_memories_expires_at"), table_name="user_memories")
    op.drop_table("user_memories")
    # ### end Alembic commands ###
